name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: install
        run: ./scripts/dev-env/run.sh ./scripts/setup.sh
      - name: npm run lint
        run: ./scripts/dev-env/run.sh npm run lint
      - name: lint-rust.sh
        run: |
          ./scripts/dev-env/run.sh scripts/lint-rust.sh
  test-rust:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: test-rust.sh
        run: |
          ./scripts/dev-env/run.sh scripts/test-rust.sh
  test-js:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: npm install
        run: ./scripts/dev-env/run.sh ./scripts/setup.sh
      - name: npm test
        run: npm test
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
      - name: Build A32NX
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
          ./scripts/dev-env/run.sh ./scripts/build.sh --no-tty -j 4
      - name: Generate install.json
        run: |
          ./scripts/dev-env/run.sh node ./scripts/fragment.js

          cp ./build-modules/modules.json ./flybywire-aircraft-a320-neo/install.json
          ./scripts/dev-env/run.sh node ./scripts/install-source.js
      - name: Upload PR artifact
        uses: actions/upload-artifact@v2
        with:
          name: A32NX
          path: ./**/flybywire-aircraft-a320-neo/
